<?php
$titel = 'Artist löschen';
$this->headTitle($titel);
?>

<h1><?php echo $this->escapeHtml($titel); ?></h1>

<p> Möchtest du den Song wirklich löschen? <br /><br />
    <?php echo 'Name: ' . $this->escapeHtml($song->getName()); ?>
    <?php echo '<br /> gesungen von: ' ; ?>
    
</p>

<?php 
$url = $this->url('song', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));

?>

<form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $song->getId(); ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>


<?php
    echo $this->render('album/song/menu/menu.phtml');
?>
