<?php
    $title = 'Artist editieren';
    $this->headTitle($titel);
?>
 <h3><?php echo $this->escapeHtml($titel); ?></h3>
<?php
    $form->setAttribute('action', $this->url('song', array('action' => 'edit')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('name'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
 
    echo $this->render('album/song/menu/menu.phtml');
