<div>
    <h3>suchen</h3>
    <table border="1">
        <colgroup width="200" span="3"></colgroup>
        <tr><th colspan="3" align=center><?php echo $titel; ?></th></tr>
        <tr>
        <?php
            foreach ($spaltenkoepfe as $spaltenkopf) {
                echo '<th>' . $spaltenkopf . '</th>';
            }
        ?>
        </tr>
        <?php
            foreach ($artisten as $song) {
                echo '<tr><td>' . $this->escapeHtml($song->getName()) . 
                        '</td><td align=right>' . $this->escapeHtml($song->getArtist_id()) .
                    '</td></tr>';
            }
        ?>
    </table>
    
<?php 
    echo $this->render('album/song/menu/menu.phtml');
?>
</div>